CREATE DATABASE IF NOT EXISTS news_analyzer;

USE news_analyzer;

CREATE TABLE IF NOT EXISTS AUTHOR (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	LAST_NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    CONSTRAINT UC_FULLNAME UNIQUE (LAST_NAME, FIRST_NAME)
);

CREATE TABLE IF NOT EXISTS SITE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS CATEGORY (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ARTICLE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ARTICLE_ID VARCHAR(255) NOT NULL,
    AUTHOR_ID INT,
    SITE_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    ARTICLE_LENGTH INT NOT NULL,
    PUBLISHED_AT DATETIME,
    CATEGORY_ID INT,
    CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
    CONSTRAINT FK_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID),
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE IF NOT EXISTS COMMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ARTICLE_ID INT NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    SUBMITTED_AT DATETIME NOT NULL,
    CONSTRAINT FK_ARTICLE FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(ID)
);