USE sys;
DROP DATABASE news_analyzer;

CREATE DATABASE news_analyzer;
USE news_analyzer;

CREATE TABLE USER_TYPE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE USER (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	LAST_NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    TYPE INT NOT NULL,
    CONSTRAINT FK_TYPE FOREIGN KEY (TYPE) REFERENCES USER_TYPE(ID),
    CONSTRAINT UC_FULLNAME UNIQUE (LAST_NAME, FIRST_NAME)
);

CREATE TABLE SITE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE CATEGORY (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE ARTICLE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    EXTERNAL_ID VARCHAR(255) NOT NULL,
    AUTHOR_ID INT,
    SITE_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    LENGTH INT NOT NULL,
    PUBLISHED_AT DATETIME,
    CATEGORY_ID INT,
    COMMENT_COUNT INT,
    CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID),
    CONSTRAINT FK_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID),
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
    CONSTRAINT CK_LENGTH CHECK(LENGTH > 0)
);

-- Dieser Index wird für die Visualisierung über Zeit verwendet. Wichtig
-- dabei ist die Ursprungsseite sowie das Veroeffentlichungsdatum
CREATE INDEX IX_ARTICLE_TIME ON ARTICLE (SITE_ID, PUBLISHED_AT);