USE news_analyzer;

CREATE OR REPLACE VIEW WEEKDAY_STATISTIC
AS
SELECT
	CASE A.DAY_OF_WEEK
      WHEN 0 THEN 'Montag'
      WHEN 1 THEN 'Dienstag'
      WHEN 2 THEN 'Mittwoch'
      WHEN 3 THEN 'Donnerstag'
      WHEN 4 THEN 'Freitag'
      WHEN 5 THEN 'Samstag'
      WHEN 6 THEN 'Sonntag'
	END AS DAY_OF_WEEK
,   S.NAME AS SITE_NAME
,   PUBLISHED
FROM (
	SELECT
		  WEEKDAY(A.PUBLISHED_AT) AS DAY_OF_WEEK
		, SITE_ID
		, COUNT(*) AS PUBLISHED
	 FROM ARTICLE A
	 GROUP BY WEEKDAY(A.PUBLISHED_AT), SITE_ID
) A
JOIN SITE S ON A.SITE_ID = S.ID
ORDER BY A.DAY_OF_WEEK, S.ID
;

CREATE OR REPLACE VIEW PUB_STATISTIC
AS
SELECT COUNT(*) AS PUBLISHED
, DATE(PUBLISHED_AT) AS PUB_DATE
, S.NAME AS SITE_NAME
FROM ARTICLE A
JOIN SITE S ON A.SITE_ID = S.ID
GROUP BY DATE(PUBLISHED_AT), SITE_ID
ORDER BY DATE(PUBLISHED_AT)
;

CREATE OR REPLACE VIEW CATEGORY_SUMMARY
AS
SELECT
	COUNT(*) AS CNT,
	C.NAME AS C_NAME
	FROM ARTICLE A
	JOIN CATEGORY C ON A.CATEGORY_ID = C.ID
	GROUP BY C.ID
	ORDER BY CNT
;