USE news_analyzer;

CREATE OR REPLACE VIEW ARTICLES_PER_AUTHOR
AS
SELECT
	  AT.FIRST_NAME
	, AT.LAST_NAME
	, S.NAME
	, COUNT(*) AS ARTICLES_WRITTEN
FROM
	ARTICLE A
	JOIN AUTHOR AT ON A.AUTHOR_ID = AT.ID
	JOIN SITE S ON A.SITE_ID = S.ID
	JOIN CATEGORY C ON A.CATEGORY_ID = C.ID
GROUP BY
	AT.LAST_NAME, AT.FIRST_NAME, S.NAME
ORDER BY
	ARTICLES_WRITTEN DESC;

CREATE OR REPLACE VIEW WEEKLY_STATISTIC
AS
SELECT
