CREATE DATABASE IF NOT EXISTS news_analyzer;

USE news_analyzer;

CREATE TABLE IF NOT EXISTS AUTHOR (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	LAST_NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    CONSTRAINT UC_FullName UNIQUE (LAST_NAME, FIRST_NAME)
);

CREATE TABLE IF NOT EXISTS SITE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS CATEGORY (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ARTICLE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ARTICLE_ID VARCHAR(255) NOT NULL,
    AUTHOR_ID INT,
    SITE_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    ARTICLE_LENGTH INT NOT NULL,
    COMMENT_COUNT INT,
    PUBLISHED_AT DATETIME,
    CATEGORY_ID INT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
    FOREIGN KEY (SITE_ID) REFERENCES SITE(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);